const shared = {
  spacing: {
    xs: '4px',
    sm: '8px',
    md: '12px',
    lg: '16px',
    xl: '24px',
  },
  font: {
    family: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    size: {
      sm: '12px',
      md: '14px',
      lg: '16px',
      xl: '20px',
    },
  },
  borderRadius: '6px',
};

export const lightTheme = {
  ...shared,
  priority: {
    LOW: { color: '#2e7d32', bg: '#e8f5e9' },
    MEDIUM: { color: '#e65100', bg: '#fff3e0' },
    HIGH: { color: '#c62828', bg: '#ffebee' },
    URGENT: { color: '#ad1457', bg: '#fce4ec' },
  },
  colors: {
    background: '#ffffff',
    surface: '#f5f5f5',
    text: '#1a1a1a',
    textSecondary: '#6b7280',
    border: '#e5e7eb',
    accent: '#3b82f6',
    accentHover: '#2563eb',
    today: '#eff6ff',
    boundary: '#9ca3af',
    error: '#ef4444',
    inputBg: '#ffffff',
    inputBorder: '#d1d5db',
    cardBg: '#ffffff',
    cardBorder: '#e5e7eb',
    cardShadow: '0 1px 3px rgba(0,0,0,0.08)',
    holidayBg: '#fef2f2',
    holidayText: '#dc2626',
    deleteHover: '#ef4444',
    surfaceHover: '#e8eaed',
    headerBg: '#fafbfc',
    borderLight: '#dde1e6',
    todayBadge: '#3b82f6',
    holidayBorder: '#fecaca',
    addButtonBorder: '#d1d5db',
    addButtonText: '#6b7280',
    overlay: 'rgba(0, 0, 0, 0.4)',
  },
};

export const darkTheme = {
  ...shared,
  priority: {
    LOW: { color: '#4ade80', bg: '#1a3a1a' },
    MEDIUM: { color: '#fbbf24', bg: '#3a2a1a' },
    HIGH: { color: '#fb923c', bg: '#3a1a1a' },
    URGENT: { color: '#fb7185', bg: '#4a1a2a' },
  },
  colors: {
    background: '#121212',
    surface: '#1e1e1e',
    text: '#e4e4e7',
    textSecondary: '#a1a1aa',
    border: '#2e2e2e',
    accent: '#60a5fa',
    accentHover: '#3b82f6',
    today: '#1e2a3a',
    boundary: '#52525b',
    error: '#f87171',
    inputBg: '#2a2a2a',
    inputBorder: '#3a3a3a',
    cardBg: '#2a2a2a',
    cardBorder: 'transparent',
    cardShadow: '0 1px 3px rgba(0,0,0,0.3)',
    holidayBg: '#3a2020',
    holidayText: '#fca5a5',
    deleteHover: '#dc2626',
    surfaceHover: '#2a2a2a',
    headerBg: '#181818',
    borderLight: '#3a3a3a',
    todayBadge: '#60a5fa',
    holidayBorder: '#5a3030',
    addButtonBorder: '#3a3a3a',
    addButtonText: '#a1a1aa',
    overlay: 'rgba(0, 0, 0, 0.6)',
  },
};

export type Theme = typeof lightTheme;
